name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - master  # Adjust if you want to trigger on a different branch

permissions:
  id-token: write   # Allows the workflow to request an OIDC token for AWS role assumption
  contents: read    # Allows read access to the repository contents

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using STS (assume role via OIDC)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::049789986873:role/github-devsecops
          aws-region: us-east-1

      # Step 3: Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Register Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json file://.github/workflows/defectdojo-task-def.json

      - name: Deploy DefectDojo Service
        run: |
          aws ecs create-service \
            --cluster defectdojo-cluster \
            --service-name defectdojo-service \
            --task-definition defectdojo-task \
            --desired-count 1 \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-090dc98e525d9165a],securityGroups=[sg-0a6a475d4bec5d17a],assignPublicIp=ENABLED}"
      
      - name: Get DefectDojo Public IP
        run: |
          TASK_ARN=$(aws ecs list-tasks --cluster defectdojo-cluster --service defectdojo-service --query "taskArns[0]" --output text)
          ENI_ID=$(aws ecs describe-tasks --cluster defectdojo-cluster --tasks $TASK_ARN --query "tasks[0].attachments[0].details[?name=='networkInterfaceId'].value" --output text)
          PUBLIC_IP=$(aws ec2 describe-network-interfaces --network-interface-ids $ENI_ID --query "NetworkInterfaces[0].Association.PublicIp" --output text)
          echo "DEFECTDOJO_URL=http://$PUBLIC_IP:8080" >> $GITHUB_ENV

#Made changes to github-devsecops-policy 