name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - master  # Adjust if you want to trigger on a different branch

permissions:
  id-token: write   # Allows the workflow to request an OIDC token for AWS role assumption
  contents: read    # Allows read access to the repository contents

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using STS (assume role via OIDC)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::049789986873:role/github-devsecops
          aws-region: us-east-1

      ###########################################
      # SCA/ Dependency Checking with NPM Audit
      ###########################################

      # Basic Node Setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # NPM Setup
      - name: Install dependencies
        working-directory: bank_app/site
        run: npm install

      # NPM Audit and saving file as JSON Report
      - name: Run npm audit and output JSON
        working-directory: bank_app/site
        run: npm audit --json > audit.json || true

      # Report Upload as Github Artifact -- Available in Workflow Summary to Download
      - name: Upload audit report artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: bank_app/site/audit.json

      # Upload report to DefectDojo - test2
      - name: Upload NPM Audit Scan Report to DefectDojo
        run: |
          curl -k -X POST "$DEFECTDOJO_URL/api/v2/reimport-scan/" \
          -H "Authorization: Token $DEFECTDOJO_API_KEY" \
          -H "Content-Type: multipart/form-data" \
          -F "scan_type=NPM Audit v7+ Scan" \
          -F "product_name=Product1" \
          -F "file=@bank_app/site/audit.json" \
          -F "engagement_name=Continuous Testing" \
          -F "close_old_findings=true" \
        env:
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}